name: react
on:
  push:
    branches:
      - main
      - release/*
      - snapshot/*
    tags:
      - v*
  pull_request:
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' || github.ref_name != 'main' }}

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - uses: perses/github-actions@46131ce1b8557dd8c4dc5af854b5abbad36679df # v0.11.0
      - uses: ./.github/perses-ci/actions/setup_environment
        with:
          enable_npm: true
          nvmrc_path: "./ui/.nvmrc"
      - name: install deps
        run: cd ./ui && npm ci
      - run: cd ./ui && npm run lint
  type_check:
    name: "type check"
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - uses: perses/github-actions@46131ce1b8557dd8c4dc5af854b5abbad36679df # v0.11.0
      - uses: ./.github/perses-ci/actions/setup_environment
        with:
          enable_npm: true
          nvmrc_path: "./ui/.nvmrc"
      - name: install deps
        run: cd ./ui && npm ci
      - run: cd ./ui && npm run type-check
  test:
    name: "unit test"
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - uses: perses/github-actions@46131ce1b8557dd8c4dc5af854b5abbad36679df # v0.11.0
      - uses: ./.github/perses-ci/actions/setup_environment
        with:
          enable_npm: true
          nvmrc_path: "./ui/.nvmrc"
      - name: install deps
        run: cd ./ui && npm ci
      - run: cd ./ui && npm run test
